# Generated by Django 3.2.13 on 2022-08-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0002_addstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddStudents',
            new_name='AddStudent',
        ),
    ]
