# Generated by Django 3.2.13 on 2022-08-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0003_rename_addstudents_addstudent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addstudent',
            old_name='roll_no',
            new_name='roll_number',
        ),
    ]
