# Generated by Django 3.2.13 on 2022-08-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsite', '0004_rename_roll_no_addstudent_roll_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddStudent',
        ),
    ]
